lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "lox-gc"
rust-version.workspace = true
version.workspace = true

[dependencies]
arrayvec.workspace = true
lox-mmap = { path = "../lox-mmap" }
