lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "lox-vm"
rust-version.workspace = true
version.workspace = true

[dependencies]
arrayvec.workspace = true
lox-bytecode.workspace = true
lox-gc = { path = "../lox-gc" }
